// apps/frontend/chat/src/shared/ui/avatar/avatar.tsx
import { UserCircleIcon } from '@heroicons/react/24/outline';

import type { FC } from 'react';

interface IAvatarProps {
    imageSrc?: string
}

export const Avatar: FC<IAvatarProps> = ({ imageSrc }) => (
  <div className='chat:rounded-full chat:w-15 chat:h-15 chat:overflow-hidden chat:bg-brown/30 chat:dark:bg-dark'>
    {!imageSrc ?
      <UserCircleIcon className='chat:w-full chat:h-full chat:dark:stroke-white chat:stroke-white/80' />
      : <img src={imageSrc} className='chat:w-full chat:h-full' alt='avatar'/>
    }
  </div>

);

// apps/frontend/sidebar/src/shared/ui/avatar/avatar.vue
<script setup lang="ts">
import { UserCircleIcon } from '@heroicons/vue/24/outline';
const {src} = defineProps({
  src: {
    type: String,
    default: '',
  }
});

</script>


<template>
  <div
    class="sidebar:w-10 sidebar:h-10 sidebar:rounded-full sidebar:bg-brown/30
    sidebar:flex sidebar:items-center sidebar:justify-center
    sidebar:dark:bg-dark sidebar:cursor-pointer"
  >
    <img
      v-if="src"
      :src="src"
      class="sidebar:w-full sidebar:h-full sidebar:rounded-full
        sidebar:object-cover sidebar:object-center"
    />
    <UserCircleIcon v-else class="sidebar:w-full sidebar:h-full sidebar:dark:stroke-white sidebar:stroke-white/80" />
  </div>
</template>

<script lang="ts">

export default {
  name: 'Avatar',
};
</script>
